[
    {
        "snapshot_id": "aaeaada5-5320-4332-a203-7d808c9fac3e",
        "name": "RED",
        "created_at": 1778722194,
        "description": "Snapshot 'RED' taken on 2026-05-14 at 01:29:54",
        "filename": "RED.gns3snapshot",
        "project_id": "d921435d-890b-4a89-b1a6-ba1b13d6ab29"
    }
]